name: Compile Geodot for Mac OS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, gdextension ]
  pull_request:
    branches: [ master, gdextension ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache generated godot-cpp bindings
        id: cache-bindings
        uses: actions/cache@v2
        env:
          cache-name: godot-cpp-cache
        with:
          path: godot-cpp
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.ref_name }}-${{ hashFiles('godot-cpp') }}-osx

      - name: Initialize submodules
        if: steps.cache-bindings.outputs.cache-hit != 'true'
        run: git submodule update --init --recursive
        
      - name: Install dependencies
        run: |
          brew install gdal
          brew install scons
      
      - name: Generate Godot-CPP bindings
        if: steps.cache-bindings.outputs.cache-hit != 'true'
        run: scons platform=macos generate_bindings=yes
        working-directory: godot-cpp
        
      - name: Build Geodot
        run: scons platform=osx  osgeo_path=$(brew info gdal | grep '/usr/local' | cut -d ' ' -f 1)
        
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: |
            demo
